server.tcp.port=8080

server.udp.port=9876

server.game.duration.seconds=600

server.max.mistakes=4

server.save.interval.seconds=30

server.storage.dir=storage

server.puzzle.file=Connections_Data.json

server.thread.pool.size=10