package shared.dto;
public enum ErrorCode {
    USERNAME_ALREADY_REGISTERED,
    INCORRECT_PASSWORD,
    USER_NOT_LOGGED_IN,
    MALFORMED_PROPOSAL,
    GAME_NOT_FOUND,
    NEW_USERNAME_ALREADY_TAKEN,
    INTERNAL_ERROR,
    WORDS_ALREADY_GROUPED,
    UNKNOWN_WORDS_IN_PROPOSAL,
    GAME_NOT_CURRENT,
    PLAYER_ALREADY_COMPLETED_GAME
}
