package shared;

public enum ErrorCode {
    INVALID_REQUEST("INVALID_REQUEST"),
    INVALID_CREDENTIALS_FORMAT("INVALID_CREDENTIALS_FORMAT"),
    USERNAME_ALREADY_EXISTS("USERNAME_ALREADY_EXISTS"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    INVALID_USERNAME_OR_PASSWORD("INVALID_USERNAME_OR_PASSWORD"),
    UNAUTHORIZED_OR_USER_MISMATCH("UNAUTHORIZED_OR_USER_MISMATCH"),
    INVALID_USERNAME("INVALID_USERNAME"),
    TARGET_USERNAME_TAKEN("TARGET_USERNAME_TAKEN"),
    USER_NOT_LOGGED_IN("USER_NOT_LOGGED_IN"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    MALFORMED_PROPOSAL("MALFORMED_PROPOSAL"),
    MALFORMED_PROPOSAL_OR_GAME_OVER("MALFORMED_PROPOSAL_OR_GAME_OVER"),
    INVALID_WORDS_NOT_IN_PUZZLE("INVALID_WORDS_NOT_IN_PUZZLE"),
    WORDS_ALREADY_SOLVED("WORDS_ALREADY_SOLVED"),
    DUPLICATE_PROPOSAL("DUPLICATE_PROPOSAL"),
    GAME_NOT_FOUND("GAME_NOT_FOUND"),
    PLAYER_NOT_FOUND("PLAYER_NOT_FOUND"),
    UNKNOWN_REQUEST("UNKNOWN_REQUEST");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }
}